# ========================
# PostgreSQL
# ========================
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/collectobjet
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ========================
# JWT
# ========================
jwt.secret=uneCleTresLongueEtSecretePourProductionAChanger123456789
jwt.expiration=86400000

# ========================
# Cloudinary
# ========================
cloudinary.cloud-name=drtaxpijo
cloudinary.api-key=257852776176651
cloudinary.api-secret=DxMruZfNP5AL7u9LoygWp1l0yAQ
# ========================
# SMS
sms.enabled=false
sms.provider=africastalking

# Africa's Talking
africastalking.username=sandbox
africastalking.api-key=atsk_59d21af19438bc36b9abd316a0d609c2d372ae4e60ec112f8db20b492e4a6e406da965b6